use_frameworks!

platform :ios, '8.0'

target 'HCNetWorking_Example' do
  pod 'HCNetWorking', :path => '../'

  target 'HCNetWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
